models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - myproject:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory myproject --reload-on-changes myproject/myproject/wsgi.py"